server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LT3211/springcloud.git
          searchPaths: config
          username: LT3211
          password: Lt123456@
        label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
