server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LT3211/springcloud.git
          searchPaths: config
          username: LT3211 #git账号
          password:        #git密码
        label: master      #分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
